platform :ios, '8.0'
use_frameworks!
target 'BraveDream' do
pod 'Alamofire', '~> 4.4'
pod 'SnapKit', '~> 3.2.0'
pod 'EZSwiftExtensions'
pod 'AlamofireObjectMapper', '~> 4.0'
pod 'YYCache'
pod 'Kingfisher', '~> 3.6.2'
pod 'ESTabBarController-swift'
pod 'KMNavigationBarTransition'
pod 'IQKeyboardManagerSwift'
pod 'FSPagerView'
end
